#ifndef  __Protocol_H
#define  __Protocol_H

enum ProtocolList
{
	P_CONNECTIONSUCCESS_ACK = 100,

	P_TESTPACKET1_REQ, P_TESTPACKET1_ACK,
	P_TESTPACKET2_REQ, P_TESTPACKET2_ACK,
	P_TESTPACKET3_REQ, P_TESTPACKET3_ACK
};

#endif